name: Deploy Bot

on:
  push:
    branches:
      - feature   # деплой только при пуше в feature

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # если папки ещё нет — клонируем
            if [ ! -d /opt/mybot/.git ]; then
              rm -rf /opt/mybot
              git clone https://github.com/Legacyyy777/remnawave-bedolaga-telegram-bot_777.git /opt/mybot
            fi

            cd /opt/mybot

            # обновляем и переключаемся на feature
            git fetch origin
            git checkout feature
            git reset --hard origin/feature

            # пересобираем и запускаем контейнер
            docker compose build
            docker compose up -d
